### PR TITLE
Fix handling of magic values in parseQuery.

### LINKED ISSUE #855: We need additional unittests for parseQuery
ParseQuery is never tested on its own, but always through more of integration tests etc. We should test it better because it is something subtle and can break easily.

### PR DESCRIPTION
**Pull request by Kangz**
JSON.parse's reviver modifies the key, not the value like
parseParamValueReviver was doing. Also this commit simplifies a bit the
handling of -0 in json_param_value.ts.

Adds tests for magic values and also add parseQuery tests because it had
only indirect test coverage.

Fixes #855

<hr>

**Author checklist for test code/plans:**

- [ ] All outstanding work is tracked with "TODO" in a test/file description or `.unimplemented()` on a test.
- [ ] New helpers, if any, are documented using `/** doc comments */` and can be found via `helper_index.txt`.
- [ ] (Optional, sometimes not possible.) Tests pass (or partially pass without unexpected issues) in an implementation. (Add any extra details above.)

**[Reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md) for test code/plans:** (Note: feel free to pull in other reviewers at any time for any reason.)

- [ ] The test path is reasonable, the [description](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) "describes the test, succinctly, but in enough detail that a reader can read only the test plans in a file or directory and evaluate the completeness of the test coverage."
- [ ] Tests appear to cover this area completely, except for outstanding TODOs. Validation tests use control cases.
    (This is critical for coverage. Assume anything without a TODO will be forgotten about forever.)
- [ ] Existing (or new) test helpers are used where they would reduce complexity.
- [ ] TypeScript code is readable and understandable (is unobtrusive, has reasonable type-safety/verbosity/dynamicity).

### CODE REVIEW

File: src/common/internal/query/json_param_value.ts [hunk 1]
```diff
@@ -68,12 +71,8 @@ export function stringifyParamValueUniquely(value: JSONWithUndefined): string {
 // 'any' is part of the JSON.parse reviver interface, so cannot be avoided.
 // eslint-disable-next-line  @typescript-eslint/no-explicit-any
 function parseParamValueReviver(k: string, v: any): any {
-  if (k === jsNegativeZeroMagicValue) {
-    return -0;
-  }
-
-  if (fromStringMagicValue.has(k)) {
-    return fromStringMagicValue.get(k);
+  if (fromStringMagicValue.has(v)) {
```
Comment (Kangz) [inline src/common/internal/query/json_param_value.ts:74]: The fix is the switch from `k` to `v` here and in the return.

**Review by ben-clayton — APPROVED** [review]

**Comment by Kangz** [comment]
Thanks!
