### PR TITLE
Test that DOMExceptions from WebGPU always have stacks

### LINKED ISSUE #3103: Test that DOMExceptions from WebGPU always have stacks
I'm working on a regression test for https://chromium-review.googlesource.com/c/chromium/src/+/4978198
Entry points that can throw or reject with an DOMException (or GPUPipelineError)

- GPUPipelineError
  - [x] createRenderPipelineAsync
  - [x] createComputePipelineAsync
  - [ ] ~`new GPUPipelineError`~. don't think we need to guarantee this, as `new DOMException` is not consistent across browsers either
- [x] requestDevice (OperationError)
- [x] createBuffer (RangeError)
- [x] mapAsync (early OperationError, AbortError, late OperationError)
- [ ] ~mapAsync (RangeError)~. don't think we can test this
- [x] getMappedRange
- [x] writeBuffer
- [x] copyExternalImageToTexture
- [x] popErrorScope
- [x] getCurrentTexture (InvalidStateError)
- [x] setBindGroup (RangeError)
- [ ] importExternalTexture (SecurityError). this is apparently not tested at all. #3109
- [x] copyExternalImageToTexture (SecurityError)
- custom (non-IDL) TypeErrors
  - [x] requestDevice
  - [x] createQuerySet
  - [x] writeTimestamp
  - [x] createTexture
  - [x] createView
  - [x] configure
  - [x] createBindGroupLayout
  - [x] createRenderBundleEncoder
  - [x] createRenderPipeline
  - [x] createRenderPipelineAsync
  - [x] setBindGroup
  - [ ] at least one thing that uses GPUColor, GPUOrigin2D, GPUOrigin3D, GPUExtent3D #3110

### PR DESCRIPTION
**Pull request by kainino0x**
<details><summary>Complete list of 150 tests that break in Chromium with this change (and are fixed by the Chromium fix):</summary>
<p>

```
  webgpu:api,operation,adapter,requestDevice:limit,better_than_supported:*
  webgpu:api,operation,adapter,requestDevice:limit,worse_than_default:*
  webgpu:api,operation,adapter,requestDevice:limits,unknown:
  webgpu:api,operation,adapter,requestDevice:stale:
  webgpu:api,validation,buffer,mapping:getMappedRange,state,mapped:
  webgpu:api,validation,buffer,mapping:getMappedRange,state,mappedAgain:
  webgpu:api,validation,buffer,mapping:getMappedRange,state,mappedAtCreation:
  webgpu:api,validation,buffer,mapping:mapAsync,abort_over_invalid_error:
  webgpu:api,validation,buffer,mapping:mapAsync,invalidBuffer:
  webgpu:api,validation,buffer,mapping:mapAsync,offsetAndSizeAlignment:
  webgpu:api,validation,buffer,mapping:mapAsync,offsetAndSizeOOB:
  webgpu:api,validation,buffer,mapping:mapAsync,sizeUnspecifiedOOB:
  webgpu:api,validation,buffer,mapping:mapAsync,state,destroyed:
  webgpu:api,validation,buffer,mapping:mapAsync,state,mapped:
  webgpu:api,validation,buffer,mapping:mapAsync,state,mappedAtCreation:
  webgpu:api,validation,buffer,mapping:mapAsync,usage:
  webgpu:api,validation,buffer,mapping:unmap,state,mappingPending:
  webgpu:api,validation,capability_checks,features,texture_formats:depth_stencil_state:*
  webgpu:api,validation,capability_checks,limits,maxBindGroups:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxBindGroups:createPipelineLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxBindGroups:setBindGroup,at_over:*
  webgpu:api,validation,capability_checks,limits,maxBindingsPerBindGroup:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxBindingsPerBindGroup:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxBufferSize:createBuffer,at_over:*
  webgpu:api,validation,capability_checks,limits,maxColorAttachmentBytesPerSample:beginRenderPass,at_over:*
  webgpu:api,validation,capability_checks,limits,maxColorAttachmentBytesPerSample:createRenderBundle,at_over:*
  webgpu:api,validation,capability_checks,limits,maxColorAttachmentBytesPerSample:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxColorAttachments:beginRenderPass,at_over:*
  webgpu:api,validation,capability_checks,limits,maxColorAttachments:createRenderBundle,at_over:*
  webgpu:api,validation,capability_checks,limits,maxColorAttachments:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxComputeInvocationsPerWorkgroup:createComputePipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxComputeWorkgroupSizeX:createComputePipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxComputeWorkgroupSizeY:createComputePipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxComputeWorkgroupSizeZ:createComputePipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxComputeWorkgroupStorageSize:createComputePipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxComputeWorkgroupsPerDimension:dispatchWorkgroups,at_over:*
  webgpu:api,validation,capability_checks,limits,maxDynamicStorageBuffersPerPipelineLayout:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxDynamicUniformBuffersPerPipelineLayout:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxInterStageShaderComponents:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxInterStageShaderVariables:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxSampledTexturesPerShaderStage:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxSampledTexturesPerShaderStage:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxSampledTexturesPerShaderStage:createPipelineLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxSamplersPerShaderStage:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxSamplersPerShaderStage:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxSamplersPerShaderStage:createPipelineLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageBufferBindingSize:createBindGroup,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageBuffersPerShaderStage:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageBuffersPerShaderStage:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageBuffersPerShaderStage:createPipelineLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageTexturesPerShaderStage:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageTexturesPerShaderStage:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxStorageTexturesPerShaderStage:createPipelineLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxTextureArrayLayers:createTexture,at_over:*
  webgpu:api,validation,capability_checks,limits,maxTextureDimension1D:createTexture,at_over:*
  webgpu:api,validation,capability_checks,limits,maxTextureDimension2D:configure,at_over:*
  webgpu:api,validation,capability_checks,limits,maxTextureDimension2D:createTexture,at_over:*
  webgpu:api,validation,capability_checks,limits,maxTextureDimension2D:getCurrentTexture,at_over:*
  webgpu:api,validation,capability_checks,limits,maxTextureDimension3D:createTexture,at_over:*
  webgpu:api,validation,capability_checks,limits,maxUniformBufferBindingSize:createBindGroup,at_over:*
  webgpu:api,validation,capability_checks,limits,maxUniformBuffersPerShaderStage:createBindGroupLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxUniformBuffersPerShaderStage:createPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxUniformBuffersPerShaderStage:createPipelineLayout,at_over:*
  webgpu:api,validation,capability_checks,limits,maxVertexAttributes:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxVertexBufferArrayStride:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxVertexBuffers:createRenderPipeline,at_over:*
  webgpu:api,validation,capability_checks,limits,maxVertexBuffers:setVertexBuffer,at_over:*
  webgpu:api,validation,capability_checks,limits,minStorageBufferOffsetAlignment:createBindGroup,at_over:*
  webgpu:api,validation,capability_checks,limits,minStorageBufferOffsetAlignment:setBindGroup,at_over:*
  webgpu:api,validation,capability_checks,limits,minUniformBufferOffsetAlignment:createBindGroup,at_over:*
  webgpu:api,validation,capability_checks,limits,minUniformBufferOffsetAlignment:setBindGroup,at_over:*
  webgpu:api,validation,compute_pipeline:limits,invocations_per_workgroup,each_component:*
  webgpu:api,validation,compute_pipeline:limits,invocations_per_workgroup:*
  webgpu:api,validation,compute_pipeline:limits,workgroup_storage_size:*
  webgpu:api,validation,compute_pipeline:overrides,identifier:*
  webgpu:api,validation,compute_pipeline:overrides,uninitialized:*
  webgpu:api,validation,compute_pipeline:overrides,value,validation_error,f16:*
  webgpu:api,validation,compute_pipeline:overrides,value,validation_error:*
  webgpu:api,validation,compute_pipeline:overrides,workgroup_size,limits,workgroup_storage_size:*
  webgpu:api,validation,compute_pipeline:overrides,workgroup_size,limits:*
  webgpu:api,validation,compute_pipeline:overrides,workgroup_size:*
  webgpu:api,validation,compute_pipeline:pipeline_layout,device_mismatch:
  webgpu:api,validation,compute_pipeline:shader_module,compute:*
  webgpu:api,validation,compute_pipeline:shader_module,device_mismatch:
  webgpu:api,validation,compute_pipeline:shader_module,invalid:*
  webgpu:api,validation,error_scope:balanced_nesting:*
  webgpu:api,validation,error_scope:balanced_siblings:*
  webgpu:api,validation,error_scope:empty:
  webgpu:api,validation,render_pipeline,depth_stencil_state:depthCompare_optional:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:depthWriteEnabled_optional:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:depth_test:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:depth_write,frag_depth:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:depth_write:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:format:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:stencil_test:*
  webgpu:api,validation,render_pipeline,depth_stencil_state:stencil_write:*
  webgpu:api,validation,render_pipeline,fragment_state:color_target_exists:*
  webgpu:api,validation,render_pipeline,fragment_state:limits,maxColorAttachmentBytesPerSample,aligned:*
  webgpu:api,validation,render_pipeline,fragment_state:limits,maxColorAttachmentBytesPerSample,unaligned:*
  webgpu:api,validation,render_pipeline,fragment_state:limits,maxColorAttachments:*
  webgpu:api,validation,render_pipeline,fragment_state:pipeline_output_targets,blend:*
  webgpu:api,validation,render_pipeline,fragment_state:pipeline_output_targets:*
  webgpu:api,validation,render_pipeline,fragment_state:targets_blend:*
  webgpu:api,validation,render_pipeline,fragment_state:targets_format_filterable:*
  webgpu:api,validation,render_pipeline,fragment_state:targets_format_renderable:*
  webgpu:api,validation,render_pipeline,fragment_state:targets_write_mask:*
  webgpu:api,validation,render_pipeline,inter_stage:interpolation_sampling:*
  webgpu:api,validation,render_pipeline,inter_stage:interpolation_type:*
  webgpu:api,validation,render_pipeline,inter_stage:location,mismatch:*
  webgpu:api,validation,render_pipeline,inter_stage:location,subset:*
  webgpu:api,validation,render_pipeline,inter_stage:max_components_count,input:*
  webgpu:api,validation,render_pipeline,inter_stage:max_components_count,output:*
  webgpu:api,validation,render_pipeline,inter_stage:max_shader_variable_location:*
  webgpu:api,validation,render_pipeline,inter_stage:type:*
  webgpu:api,validation,render_pipeline,misc:pipeline_layout,device_mismatch:
  webgpu:api,validation,render_pipeline,multisample_state:alpha_to_coverage,count:*
  webgpu:api,validation,render_pipeline,multisample_state:alpha_to_coverage,sample_mask:*
  webgpu:api,validation,render_pipeline,multisample_state:count:*
  webgpu:api,validation,render_pipeline,overrides:identifier,fragment:*
  webgpu:api,validation,render_pipeline,overrides:identifier,vertex:*
  webgpu:api,validation,render_pipeline,overrides:uninitialized,fragment:*
  webgpu:api,validation,render_pipeline,overrides:uninitialized,vertex:*
  webgpu:api,validation,render_pipeline,overrides:value,validation_error,f16,fragment:*
  webgpu:api,validation,render_pipeline,overrides:value,validation_error,f16,vertex:*
  webgpu:api,validation,render_pipeline,overrides:value,validation_error,fragment:*
  webgpu:api,validation,render_pipeline,overrides:value,validation_error,vertex:*
  webgpu:api,validation,render_pipeline,primitive_state:strip_index_format:*
  webgpu:api,validation,render_pipeline,primitive_state:unclipped_depth:*
  webgpu:api,validation,render_pipeline,shader_module:device_mismatch:
  webgpu:api,validation,render_pipeline,shader_module:invalid,fragment:*
  webgpu:api,validation,render_pipeline,shader_module:invalid,vertex:*
  webgpu:api,validation,shader_module,entry_point:compute:*
  webgpu:api,validation,shader_module,entry_point:fragment:*
  webgpu:api,validation,shader_module,entry_point:vertex:*
  worker_webgpu:api,validation,buffer,mapping:getMappedRange,state,mapped:
  worker_webgpu:api,validation,buffer,mapping:getMappedRange,state,mappedAgain:
  worker_webgpu:api,validation,buffer,mapping:getMappedRange,state,mappedAtCreation:
  worker_webgpu:api,validation,buffer,mapping:getMappedRange,state,mappingPending:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,abort_over_invalid_error:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,earlyRejection:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,invalidBuffer:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,offsetAndSizeAlignment:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,offsetAndSizeOOB:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,sizeUnspecifiedOOB:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,state,destroyed:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,state,mapped:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,state,mappedAtCreation:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,state,mappingPending:
  worker_webgpu:api,validation,buffer,mapping:mapAsync,usage:
  worker_webgpu:api,validation,buffer,mapping:unmap,state,mappingPending:
```

</p>
</details>

In doing this I found some missing tests, but I didn't add TODOs for them because they weren't in tests I'm modifying here. Filing separate issues for them.

Fixes #3103
Remaining issues are #3109 #3110

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

File: src/common/framework/fixture.ts [hunk 1]
```diff
@@ -237,16 +237,26 @@ export class Fixture<S extends SubcaseBatchState = SubcaseBatchState> {
...
     this.eventualAsyncExpectation(async niceStack => {
-      const m = msg ? ': ' + msg : '';
+      const m = message ? ': ' + message : '';
       try {
         await p;
         niceStack.message = 'DID NOT REJECT' + m;
         this.rec.expectationFailed(niceStack);
       } catch (ex) {
-        niceStack.message = 'rejected as expected' + m;
+        niceStack.message = 'rejected as expected, but wrong name' + m;
```
Comment (lokokung) [inline src/common/framework/fixture.ts:252]: Hmm IIUC, this is always overridden in the subsequent `expectErrorValue` call?

File: src/common/framework/fixture.ts [hunk 2]
```diff
@@ -271,6 +285,11 @@ export class Fixture<S extends SubcaseBatchState = SubcaseBatchState> {
         this.rec.expectationFailed(new Error('threw unexpectedly' + m));
       } else {
         this.expectErrorValue(expectedError, ex, new Error(m));
+        if (checkForStackProperty) {
+          if (!(ex instanceof Error && typeof ex.stack === 'string')) {
+            this.rec.expectationFailed(new Error('missing stack' + m));
```
Comment (lokokung) [inline src/common/framework/fixture.ts:290]: nit. maybe `'threw as expected, but missing stack' + m` to be consistent with `shouldReject`?

File: src/common/util/util.ts [hunk 3]
```diff
@@ -47,15 +47,26 @@ export function assertOK<T>(value: Error | T): T {
...
   try {
     await p;
-    unreachable(msg);
+    unreachable(message);
   } catch (ex) {
-    // Assertion OK
+    // Asserted as expected
+    if (checkForStackProperty) {
+      const m = message ? ` (${message})` : '';
+      assert(ex instanceof Error && typeof ex.stack === 'string', 'missing stack property' + m);
```
Comment (lokokung) [inline src/common/util/util.ts:68]: nit. Same thing here: `'rejected as expected, but missing stack'`

File: src/common/framework/fixture.ts [hunk 4]
```diff
@@ -237,16 +237,26 @@ export class Fixture<S extends SubcaseBatchState = SubcaseBatchState> {
   }
 
   /** Expect that the provided promise rejects, with the provided exception name. */
-  shouldReject(expectedName: string, p: Promise<unknown>, msg?: string): void {
+  shouldReject(
+    expectedName: string,
+    p: Promise<unknown>,
+    { checkForStackProperty = false, message }: ExceptionCheckOptions = {}
```
Comment (lokokung) [inline src/common/framework/fixture.ts:243]: General question, should the default use case actually be `checkForStackProperty = true` instead? And then we add exceptions to that case when relevant? (I was under the impression that by default we wanted to check that, and also seems like a lot of the test changes are related to overriding the default value?)

**Review by lokokung — APPROVED** [review]

File: src/common/framework/fixture.ts (hunk 1 above)
Comment (kainino0x) [reply src/common/framework/fixture.ts:252]: You're right. We don't need this message anyway since expectErrorValue will say the same thing.

The expectationFailed below should preserve it though.
