### PR TITLE
Fix type error when trying to .writeBuffer a Float16Array

### LINKED ISSUE #1832: webgpu:api,validation,queue,writeBuffer:ranges: tries to `writeBuffer` with Float16Array
This is not valid since `Float16Array`, added in #1828, is not a real JS TypedArray type.

It fails with 
```
THREW TypeError, instead of OperationError: TypeError: Failed to execute 'writeBuffer' on 'GPUQueue': Overload resolution failed.
      at (elided: below max severity)

  - EXCEPTION: Failed to execute 'writeBuffer' on 'GPUQueue': Overload resolution failed.
    TypeError: Failed to execute 'writeBuffer' on 'GPUQueue': Overload resolution failed.
        at runTest (http://127.0.0.1:44467/third_party/webgpu-cts/src/webgpu/api/validation/queue/writeBuffer.spec.js:68:19)
        at RunCaseSpecific.fn (http://127.0.0.1:44467/third_party/webgpu-cts/src/webgpu/api/validation/queue/writeBuffer.spec.js:112:9)
```

### PR DESCRIPTION
**Pull request by zoddicus**
Fixes #1832

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

File: src/webgpu/util/conversion.ts [hunk 1]
```diff
@@ -599,8 +599,17 @@ export function f32(value: number): Scalar {
...
+  const float_16 = new Float16Array([value]);
+  // This is needed because Float16Array is not a 'real' JS TypedArray, so cannot be in the TypedArrayBufferView types.
+  // Those types are written out via GPUQueue.writeBuffer, so since it is not a TypeArray there is a type error when it
+  // is used.
+  //
+  // Currently no tests depend on reading/writing f16 values from/to the device, they are internally used as part of
+  // testing quantizeToF16, but that actually reads/writes f32 values.
+  //
+  // This hack will need to revisited one tests that write out f16 are needed.
+  const bits_16 = new Uint16Array(float_16[0]);
```
Comment (kainino0x) [inline src/webgpu/util/conversion.ts:611]: This is the same as `new Uint16Array(value)` which should make a Uint16Array with length `value`. I think you want `new Uint16Array(float_16.buffer)[0]`?

**Comment by zoddicus** [comment]
@kainino0x my understanding of your comment on the issue, https://github.com/gpuweb/cts/issues/1832#issuecomment-1244760447, is that we can just skip the Float16Array case in the tests, so I have rewritten this PR to do that instead.

**Review by kainino0x — APPROVED** [review]
