### PR TITLE
Convert `dot` to calculating permutations for vec3 and vec4

### LINKED ISSUE #2155: wgsl: `dot` CTS broken for vec3 and vec4
In https://github.com/gpuweb/cts/pull/2151 I attempted to introduce a change that would proper handle calculating the maximum interval size for dot irregardless of the addition ordering.

This is failing on Chrome to fail the CTS, looking at examples, it is pretty obvious to me that the CTS is wrong. An example:
```
  - EXPECTATION FAILED: (vec4<f32>(3.4028234663852886e+38 (0x7f7fffff), 1.0 (0x3f800000), 2.0 (0x40000000), 3.0 (0x40400000)), vec4<f32>(-1.0 (0xbf800000), 3.4028234663852886e+38 (0x7f7fffff), -2.0 (0xc0000000), -3.0 (0xc0400000)))
        returned: -13.0 (0xc1500000)
        expected: [0]
```

I need to investigate this, and either revert my original change, or push a fix.

### PR DESCRIPTION
**Pull request by zoddicus**
Fixes #2155

<hr>

**Requirements for PR author:**

- [x] All missing test coverage is tracked with "TODO" or `.unimplemented()`.
- [x] New helpers are `/** documented */` and new helper files are found in `helper_index.txt`.
- [x] Test behaves as expected in a WebGPU implementation. (If not passing, explain above.)

**Requirements for [reviewer sign-off](https://github.com/gpuweb/cts/blob/main/docs/reviews.md):**

- [ ] Tests are properly located in the test tree.
- [ ] [Test descriptions](https://github.com/gpuweb/cts/blob/main/docs/intro/plans.md) allow a reader to "read only the test plans and evaluate coverage completeness", and accurately reflect the test code.
- [ ] Tests provide complete coverage (including validation control cases). **Missing coverage MUST be covered by TODOs.**
- [ ] Helpers and types promote readability and maintainability.

When landing this PR, be sure to make any necessary issue status updates.

### CODE REVIEW

File: src/webgpu/util/math.ts [hunk 1]
```diff
@@ -875,3 +875,35 @@ export function cartesianProduct<T>(...inputs: T[][]): T[][] {
...
+  if (input.length === 1) {
+    return [input];
+  }
+
+  if (input.length === 2) {
+    return [input, [input[1], input[0]]];
+  }
+
+  const result: T[][] = [];
+  input.forEach((head, idx) => {
```
Comment (ben-clayton) [inline src/webgpu/util/math.ts:900]: Nifty!

File: src/webgpu/util/math.ts [hunk 2]
```diff
@@ -875,3 +875,35 @@ export function cartesianProduct<T>(...inputs: T[][]): T[][] {
 
   return result;
 }
+
+/** @returns all of the permutations of an array
+ *
+ * Recursively calculates all of the permutations, does not cull duplicate
```
Comment (ben-clayton) [inline src/webgpu/util/math.ts:881]: `does not cull duplicate entries` - what do you mean by this? Seems like an unexpected thing for this function to do.

**Review by ben-clayton — APPROVED** [review]
Great job!

File: src/webgpu/util/math.ts (hunk 2 above)
Comment (zoddicus) [reply src/webgpu/util/math.ts:881]: If you were ask for permutations of [1, 1] it will return [[1, 1], [1, 1]], instead of just [1,1]. The caller should remove duplicates in the return if they care.

Comment (zoddicus) [reply src/webgpu/util/math.ts:881]: culling duplicates is a pain, because we are operating on array of arrays, so .includes() doesn't work, since it will do a shallow comparison of the objects, not an element-by-element comparison of the contents.

File: src/webgpu/util/math.ts (hunk 1 above)
Comment (zoddicus) [reply src/webgpu/util/math.ts:900]: Thanks, I probably could re-organize this to be iterative instead of recursive, but I am leaning towards doing the thing I can prove is correct/implement easily, and iterate if it is too hot, since it is only being used for 3 and 4 elements arrays.
